{
    'name': 'Analytic Distribution for Point of Sale',
    'version': '19.0.1.0.0',
    'category': 'Point of Sale',
    'summary': 'Assign analytic distributions to POS accounting entries automatically',
    'description': (
        'Allows configuring an analytic distribution per POS configuration. '
        'The distribution is automatically applied to income-statement journal '
        'entry lines generated by session closing and customer invoices. '
        'A one-time backfill action is available to apply the distribution to '
        'existing historical entries in Replace or Merge mode.'
    ),
    'author': 'Mohamed Maati',
    'depends': ['point_of_sale', 'account', 'analytic'],
    'data': [
        'security/ir.model.access.csv',
        'views/pos_analytic_history_wizard_views.xml',
        'views/pos_config_views.xml',
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
    'post_uninstall_hook': 'post_uninstall_hook',
}
